CREATE TABLE CDS
(
 ID NUMBER(4),
 ALBUM VARCHAR2(25),
 ARTISTA VARCHAR2(25),
 ANO NUMBER(4)
);
ALTER TABLE CDS ADD CONSTRAINT CDSPK PRIMARY KEY(ID);
CREATE SEQUENCE S_CDS;


SELECT * FROM CDS;


CREATE TABLE LOG_TRIGGER
(
 LOG VARCHAR2(50)
);

/
CREATE OR REPLACE TRIGGER LOG_CDS 
AFTER INSERT ON CDS
FOR EACH ROW

DECLARE

BEGIN
INSERT INTO LOG_TRIGGER (LOG) VALUES ('TESTE INSERT');

END LOG_CDS;
/

SELECT * FROM LOG_TRIGGER;

INSERT INTO CDS (ID,ALBUM,ARTISTA,ANO) VALUES (5,'PAULO','VIANA',1970);